# Generated by Django 5.2.3 on 2025-06-19 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_whatsapp_sent_to_business_eventinquiry_email_sent_to_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinquiry',
            name='email',
        ),
    ]
