# Generated by Django 5.2.3 on 2025-06-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_eventinquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
