# Generated by Django 5.2.3 on 2025-06-11 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Corporate', 'Corporate'), ('Anniversary', 'Anniversary'), ('Engagement', 'Engagement'), ('Reception', 'Reception'), ('Other', 'Other')], max_length=20)),
                ('budget_range', models.CharField(choices=[('1-5 th', '1-5 th'), ('5-10 th', '5-10 th'), ('10-20 th', '10-20 th'), ('20-50 th', '20-50 th'), ('50+ th', '50+ th')], max_length=20)),
                ('additional_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('whatsapp_sent_to_business', models.BooleanField(default=False)),
                ('whatsapp_sent_to_customer', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
