# Generated by Django 5.2.3 on 2025-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinquiry',
            old_name='whatsapp_sent_to_business',
            new_name='email_sent_to_business',
        ),
        migrations.RenameField(
            model_name='eventinquiry',
            old_name='whatsapp_sent_to_customer',
            new_name='email_sent_to_customer',
        ),
        migrations.AddField(
            model_name='eventinquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='eventinquiry',
            name='sms_sent_to_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventinquiry',
            name='sms_sent_to_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventinquiry',
            name='budget_range',
            field=models.CharField(blank=True, choices=[('1-5 th', '1-5 th'), ('5-10 th', '5-10 th'), ('10-25 th', '10-25 th'), ('25-50 th', '25-50 th'), ('50-100 th', '50-100 th'), ('100+ th', '100+ th')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventinquiry',
            name='event_type',
            field=models.CharField(choices=[('Corporate Event', 'Corporate Event'), ('Wedding', 'Wedding'), ('Birthday Party', 'Birthday Party'), ('Conference', 'Conference'), ('Product Launch', 'Product Launch'), ('Networking Event', 'Networking Event'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Exhibition', 'Exhibition'), ('Other', 'Other')], max_length=50),
        ),
    ]
